### PR TITLE
tests: Convert runtime tests to subtests

### PR DESCRIPTION
**Pull request by cognifloyd**
I use Goland to run `go test`. At least with Goland, `testing.Run()` improves the output and test selection. And it makes it easier to see which subtest has failed.

As I develop and refactor, I would really like to see this everywhere. This starts with all tests under `runtime/`.
After this is merged I can prepare another one that does `executor/`.

### CODE REVIEW

**Review by kneal — DISMISSED** [review]
LGTM 🐬  😍

**Review by jbrockopp — DISMISSED** [review]
LGTM

**Review by wass3r — APPROVED** [review]
thanks for this! i like this approach better as well.

**Review by jbrockopp — APPROVED** [review]
LGTM

**Pull request merged**
