### PR TITLE
refactor: silence lint issues

### PR DESCRIPTION
**Pull request by cognifloyd**
These are already silenced in several other places. So, let's get reviewdog full-review to stop complaining.

### CODE REVIEW

**Comment by cognifloyd** [comment]
:tada: This makes `reviewdog / full-revew` green!

**Review by wass3r — COMMENTED** [review]
hmm. there are no changes ?

**Comment by cognifloyd** [comment]
I targeted the wrong branch. dang it.

**Comment by cognifloyd** [comment]
@wass3r Please see #307 instead. :facepalm:

**Pull request closed without merging**
