### PR TITLE
feat: add option to run with TLS

### PR DESCRIPTION
**Pull request by meinenec**
Allows serving over https if certs are provided.

### CODE REVIEW

**Review by kneal — COMMENTED** [review]
Does this limit someone from being able to run with an HTTP configuration?

Like if I'm running a local stack or can I run HTTP or can I chose to deploy it without HTTPS?

**Comment by meinenec** [comment]
> Does this limit someone from being able to run with an HTTP configuration?
> 
> Like if I'm running a local stack or can I run HTTP or can I chose to deploy it without HTTPS?

Yup! That's the point of checking if certs are provided.
https://github.com/go-vela/worker/blob/3d0dc1335f93aa1001ecdbe7e4e14e500b0a978f/cmd/vela-worker/server.go#L43

**Comment by kneal** [comment]
Awesome thanks for the clarification!

**Review by kneal — APPROVED** [review]
LGTM 🐬

**Review by davidvader — APPROVED** [review]

**Pull request merged**
